### ISSUE TITLE
npm dependencies install warnings

### ISSUE THREAD

**Issue by Lakhankumawat** [dscnitp/job-provider-site#6]
![isssue#1](https://user-images.githubusercontent.com/55774240/96328194-d535ae00-105d-11eb-960a-1b6ad1d0abb3.PNG)
**When I try to install npm dependencies on client side it shows lots of deprication warnings IDK why , please help me figure it out .For server side it works fine.**

**Comment by kunalprakash1309** [comment]
I found this simple explanation here https://docs.npmjs.com/using-deprecated-packages
@Lakhankumawat

**Comment by Lakhankumawat** [comment]
I updated my npm version but it's still same maybe due to react cause i have never used it on my device ? May be due to this it maybe corrupted or do we need to install any modules before start using react ???

**Comment by kunalprakash1309** [comment]
you just need node and npm installed
@Lakhankumawat

**Comment by Lakhankumawat** [comment]
I have node js and npm installed .

**Comment by kunalprakash1309** [comment]
> I have node js and npm installed .

then there will be no problem
